version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-empleados
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: Pasword1
        MYSQL_DATABASE: control_empleados
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend-control
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/control_empleados
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pasword1

volumes:
  mysql_data: